name: SeamlessDeath
version: 1.0.0
main: com.seamlessdeath.SeamlessDeathPlugin
api-version: 1.20
author: ApexON
description: A plugin that provides seamless death experience with kill cam functionality


commands:
  seamlessdeath:
    description: Main command for SeamlessDeath plugin
    usage: /<command> [reload|toggle]
    permission: seamlessdeath.admin
    aliases: [sd, seamless]

permissions:
  seamlessdeath.use:
    description: Allows player to use seamless death functionality
    default: true
  seamlessdeath.admin:
    description: Allows access to admin commands
    default: op